### PR TITLE
Refactor Bot For Code Cleanliness, Improved Performance, and Overall Usability

### PR DESCRIPTION
**Pull request by srhinos**
This implements several improvements found in other PRs on this repository. I also took it upon myself to refactor the bot to use Asyncio to juggle tasks on the backend and threading to seperate the GUI from said backend. This means no issues with locked GUI.

I refactored out a lot of the really egregious design decisions up to a certain point and did a half assed job merging and removing a lot of unnecessary bloat. Theres still a LOT of room for improvement too now that the CV is running on asyncio too. I'm sure I'll eventually add it but this is what I felt like doing tonight.

Edit: To clairfy, this also integrates the following active PRs as well:
https://github.com/Siterizer/new-world-fishing-bot/pull/208
https://github.com/Siterizer/new-world-fishing-bot/pull/164
https://github.com/Siterizer/new-world-fishing-bot/pull/134
https://github.com/Siterizer/new-world-fishing-bot/pull/106

### CODE REVIEW

**Comment by blablub84** [comment]
can anyone share a compiled version?
otherwise as long as i apply the changes to the 27 files, and use pyton 3.8 i should be fine with the old compile guide?

**Comment by srhinos** [comment]
Yup, no dependency changes so you should be able to just run `python bot.py` as before and it should work similarly. I cba to compile a version since running it from the terminal is just easier for me.   
  
  
  
    
  

  
  
>

**Comment by Siterizer** [comment]
@srhinos @blablub84 There are some errors in this version, will try to fix them now

**Comment by Siterizer** [comment]
Okay, new release is here.
Code: https://github.com/Siterizer/new-world-fishing-bot/tree/v2.0.0
Compiled .zip: https://github.com/Siterizer/new-world-fishing-bot/releases/tag/v2.0.0

Tested it for about an hour and it's working. But will be glad about your feedback

**Comment by srhinos** [comment]
Nice, I like a lot of those changes. I see a new function for processing the image too, that might need to be shifted to be async which I can do if you want but it’s not implemented just right now so no big deal. OpenCV’s image match works a lot better in greyscale but we still want to color version for color matching so it might be helpful to leave as is or refactor the image detection   to two functions, one for color checking and the other for Template matching.   
  

  
As a side note, if you want any help maintaining the repo, happy to help out with maintaining!   Appreciate all the review you’ve given everything and there’s a few places I’d love to continue to contribute in!
  
  
  
    
  

  
  
>

**Comment by ComictypX** [comment]
Nice work @srhinos! I was also wondering if the templatematching would be faster if we switch to greyscale.

But I see that you are not using the latest version of PR #134. In commit https://github.com/Siterizer/new-world-fishing-bot/pull/134/commits/dcaf9c4a2bec4db35a2645ab827d0331af0cb3f3 I already added support for 16:10, 21:9 and 32:9 aspect ratios. 

This is also missing in the 2.0.0 Branch @Siterizer :)

**Comment by Sevenn56** [comment]
Hello buddies ! I have to admit that i'm a begginer and i dont know how to modify or use your version ? Can you do à step by step to show me ? Or add me discord Seven#9428
Thanks buddies

**Comment by tallglen** [comment]
> Okay, new release is here. Code: https://github.com/Siterizer/new-world-fishing-bot/tree/v2.0.0 Compiled .zip: https://github.com/Siterizer/new-world-fishing-bot/releases/tag/v2.0.0
> 
> Tested it for about an hour and it's working. But will be glad about your feedback

When I do a code compare between v2.0.0 and v1.2.1, the only change I see is to the README.md

I've been testing the 2 major PRs and happy to see that we have multithreading now and no more "Not Responding" problems with the GUI or inability to stop/pause fishing.

Testing srhinos' PR (main), my fish detection fails every other cast but otherwise hooks the fish almost immediately whereas the vanilla experience was a bit of randomness as to how fast it would hook the fish.

Testing NewWorldDev's PR (feature/pause-hotkey) I've had more consistent successful hooks with; nice work with the in-window stats and colorization.  @NewWorldDev have you thought about ways to animation cancel the flourish that happens when fish are caught?

**Pull request merged**
