### PR TITLE
Optimized searching for specified colors in image_recognition.py with cv::inRange()

### PR DESCRIPTION
**Pull request by ComictypX**
Iterating through a Python array with two nested for-loops is not as fast as openCV/Numpy can do it vectorized.
Therefore, I replaced the two for-loops by the OpenCV function `cv::inRange()` and the python array given by PIL with a numpy one.

I tried my best measuring the improvements with measuring the execution time of `call_appropriate_fishing_action()`:

Before:  ~0,3534 seconds
After:    ~0,09526 seconds 
== 3,71 times faster (median average bit smaller: 3,62)

Just the color finding part without template matching is ~175 - 200 times faster.

Another Upside: we now have all the color matching pixels and could do some math on them to get the area, e.g. for optimized reeling (all white pixels in mask).

### CODE REVIEW

**Comment by Marow** [comment]
@ComictypX So dont need the Fishing Positioning anymore? 
Will that work now also on higher Resolution?

**Comment by 4rak007** [comment]
> 
> 
> Iterating through a Python array with two nested for-loops is not as fast as openCV/Numpy can do it vectorized. Therefore, I replaced the two for-loops by the OpenCV function `cv::inRange()` and the python array given by PIL with a numpy one.
> 
> I tried my best measuring the improvements with measuring the execution time of `call_appropriate_fishing_action()`:
> 
> Before: ~0,3534 seconds After: ~0,09526 seconds == 3,71 times faster (median average bit smaller: 3,62)
> 
> Just the color finding part without template matching is ~175 - 200 times faster.
> 
> Another Upside: we now have all the color matching pixels and could do some math on them to get the area, e.g. for optimized reeling (all white pixels in mask).


Hello, Which file did u edit ? and if u could upload the file would be nice ty .

**Comment by 53m1k0l0n** [comment]
> > Iterating through a Python array with two nested for-loops is not as fast as openCV/Numpy can do it vectorized. Therefore, I replaced the two for-loops by the OpenCV function `cv::inRange()` and the python array given by PIL with a numpy one.
> > I tried my best measuring the improvements with measuring the execution time of `call_appropriate_fishing_action()`:
> > Before: ~0,3534 seconds After: ~0,09526 seconds == 3,71 times faster (median average bit smaller: 3,62)
> > Just the color finding part without template matching is ~175 - 200 times faster.
> > Another Upside: we now have all the color matching pixels and could do some math on them to get the area, e.g. for optimized reeling (all white pixels in mask).
> 
> Hello, Which file did u edit ? and if u could upload the file would be nice ty .

Look here: xD
[Files](https://github.com/Siterizer/new-world-fishing-bot/pull/106/files)

**Comment by Logonius** [comment]
Checked all 10 times, every line, no errors.
And he also leaves the game in the AFK, it is no longer possible to catch.

**Comment by Siterizer** [comment]
Sorry, end of the support. Statement:
https://github.com/Siterizer/new-world-fishing-bot#new-world-fishing-bot-end-of-support

**Pull request closed without merging**
